# Site Settings
title: Andrii Shylenko
locale: "en-US"
description: "Engineer, Entrepreneur, Humanist. Focusing on Embedded Systems, Robotics, and Web Technologies."
url: "https://shylenko.com"
baseurl: "" # subpath of your site, e.g. /blog
repository: "w1ne/w1ne.github.io"

# Theme Settings
theme: "minimal-mistakes-jekyll"
minimal_mistakes_skin: "dark" # "air", "aqua", "contrast", "dark", "dirt", "neon", "mint", "plum", "sunrise"
search: true

# Author / Personal Info
author:
  name: "Andrii Shylenko"
  avatar: "/images/profile-photo.jpg"
  bio: "Engineer, Entrepreneur, Humanist"
  email: "andrii@shylenko.com"
  links:
    - label: "GitHub"
      icon: "fab fa-fw fa-github"
      url: "https://github.com/w1ne"
    - label: "LinkedIn"
      icon: "fab fa-fw fa-linkedin"
      url: "https://linkedin.com/in/shylenko"
    - label: "Twitter"
      icon: "fab fa-fw fa-twitter"
      url: "https://twitter.com/andriishylenko"

# Navigation
logo: "/images/logoAS_blue_white.png"
date_format: "%Y-%m-%d"

# Plugins
plugins:
  - jekyll-include-cache
  - jekyll-feed
  - jekyll-sitemap

# Defaults
defaults:
  # _posts
  - scope:
      path: ""
      type: posts
    values:
      layout: single
      author_profile: false
      classes: wide
      read_time: true
      comments: true
      share: true
      related: true
  # pages
  - scope:
      path: ""
      type: pages
    values:
      layout: single
      author_profile: false
      classes: wide

# Sass
sass:
  style: compressed
